// ─── HARDCODED ACCOUNTS (not displayed on screen) ───────────────────────────
export const ACCOUNTS = [
  {
    id: 1,
    name: "Arjun Mehta",
    email: "arjun@skyops.com",
    password: "Sky@1234",
    role: "Senior Disruption Manager",
    badge: "SDM-001",
    avatar: "AM",
  },
  {
    id: 2,
    name: "Priya Nair",
    email: "priya@skyops.com",
    password: "Ops@5678",
    role: "Operations Analyst",
    badge: "OA-042",
    avatar: "PN",
  },
  {
    id: 3,
    name: "Rahul Sharma",
    email: "rahul@skyops.com",
    password: "Admin@999",
    role: "Hub Controller",
    badge: "HC-007",
    avatar: "RS",
  },
  {
    id: 4,
    name: "Sneha Reddy",
    email: "sneha@skyops.com",
    password: "Pass@2024",
    role: "Passenger Relations Lead",
    badge: "PRL-018",
    avatar: "SR",
  },
];

// ─── MOCK DISRUPTED FLIGHTS ──────────────────────────────────────────────────
export const FLIGHTS = [
  {
    id: "F001",
    flightNo: "SK 2047",
    origin: "HYD",
    destination: "BOM",
    scheduled: "06:15",
    status: "CANCELLED",
    reason: "Aircraft AOG – hydraulic fault",
    affectedPax: 186,
    gate: "B12",
    aircraft: "A320neo",
    priority: "CRITICAL",
    paxProcessed: 42,
    hotelIssued: 0,
    mealIssued: 0,
    reaccomIssued: 0,
  },
  {
    id: "F002",
    flightNo: "SK 3109",
    origin: "DEL",
    destination: "SIN",
    scheduled: "09:40",
    status: "DELAYED",
    reason: "ATC slot restriction – 4h delay",
    affectedPax: 234,
    gate: "C05",
    aircraft: "B787-9",
    priority: "HIGH",
    paxProcessed: 180,
    hotelIssued: 0,
    mealIssued: 210,
    reaccomIssued: 0,
  },
  {
    id: "F003",
    flightNo: "SK 1872",
    origin: "BLR",
    destination: "LHR",
    scheduled: "22:55",
    status: "DELAYED",
    reason: "Late inbound aircraft",
    affectedPax: 312,
    gate: "A01",
    aircraft: "B777-300ER",
    priority: "HIGH",
    paxProcessed: 290,
    hotelIssued: 85,
    mealIssued: 312,
    reaccomIssued: 22,
  },
  {
    id: "F004",
    flightNo: "SK 4401",
    origin: "MAA",
    destination: "DXB",
    scheduled: "14:20",
    status: "CANCELLED",
    reason: "Crew duty time violation",
    affectedPax: 144,
    gate: "D09",
    aircraft: "A330-300",
    priority: "CRITICAL",
    paxProcessed: 60,
    hotelIssued: 144,
    mealIssued: 144,
    reaccomIssued: 100,
  },
  {
    id: "F005",
    flightNo: "SK 5530",
    origin: "CCU",
    destination: "BKK",
    scheduled: "11:00",
    status: "DIVERTED",
    reason: "Destination weather – diverted to CNX",
    affectedPax: 198,
    gate: "E03",
    aircraft: "A321XLR",
    priority: "MEDIUM",
    paxProcessed: 198,
    hotelIssued: 198,
    mealIssued: 198,
    reaccomIssued: 140,
  },
  {
    id: "F006",
    flightNo: "SK 7723",
    origin: "BOM",
    destination: "JFK",
    scheduled: "01:30",
    status: "DELAYED",
    reason: "Technical – engine borescope inspection",
    affectedPax: 272,
    gate: "F14",
    aircraft: "B787-10",
    priority: "HIGH",
    paxProcessed: 100,
    hotelIssued: 272,
    mealIssued: 272,
    reaccomIssued: 0,
  },
];

// ─── HOTEL PARTNERS ──────────────────────────────────────────────────────────
export const HOTELS = [
  { id: "H1", name: "Hyatt Regency", city: "HYD", rooms: 24, rate: "₹6,800/night", stars: 5 },
  { id: "H2", name: "Novotel Airport", city: "HYD", rooms: 40, rate: "₹4,200/night", stars: 4 },
  { id: "H3", name: "ibis Styles", city: "DEL", rooms: 60, rate: "₹2,900/night", stars: 3 },
  { id: "H4", name: "JW Marriott", city: "BOM", rooms: 18, rate: "₹9,500/night", stars: 5 },
  { id: "H5", name: "Lemon Tree", city: "BLR", rooms: 35, rate: "₹3,100/night", stars: 3 },
];

// ─── MEAL TEMPLATES ──────────────────────────────────────────────────────────
export const MEAL_VOUCHERS = [
  { id: "M1", type: "Breakfast", value: "₹400", venue: "Terminal Food Court" },
  { id: "M2", type: "Lunch/Dinner", value: "₹750", venue: "Terminal Food Court" },
  { id: "M3", type: "Full Day", value: "₹1,200", venue: "Any airport outlet" },
  { id: "M4", type: "Snack", value: "₹200", venue: "Terminal vending/café" },
];

// ─── COMMS TEMPLATES ─────────────────────────────────────────────────────────
export const COMM_TEMPLATES = [
  {
    id: "C1",
    trigger: "CANCELLED",
    subject: "Important: Your flight has been cancelled",
    body: "We sincerely apologise for the cancellation of your flight {flightNo}. Our team is working to re-accommodate all affected passengers. Please proceed to the nearest Sky Airlines service desk at Gate {gate} for immediate assistance.",
  },
  {
    id: "C2",
    trigger: "DELAYED",
    subject: "Flight delay update – {flightNo}",
    body: "Your flight {flightNo} has been delayed. We expect departure at approximately {newTime}. Complimentary meal vouchers are available at the service desk. We apologise for this inconvenience.",
  },
  {
    id: "C3",
    trigger: "DIVERTED",
    subject: "Diversion notice – {flightNo}",
    body: "Due to circumstances beyond our control, flight {flightNo} has been diverted. Hotel accommodation and onward transportation will be arranged. A Sky Airlines representative will meet you on arrival.",
  },
  {
    id: "C4",
    trigger: "REACCOMMODATED",
    subject: "Your new booking confirmation – {flightNo}",
    body: "We have successfully re-accommodated you on an alternative flight. Please check your updated itinerary in the Sky Airlines app or at the check-in desk.",
  },
];
